// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateNewULID() {
  return window['go']['main']['App']['GenerateNewULID']();
}

export function ParseInput(arg1) {
  return window['go']['main']['App']['ParseInput'](arg1);
}
